### ISSUE TITLE
crashes if too laggy and m7 dragon spawn notification enabled(?)

### ISSUE THREAD

**Issue by x-yingcan-x** [AzureAaron/aaron-mod#7]
not really sure about it
```
[21:43:12] [Netty Client IO #2/INFO]: [System] [CHAT] [Aaron's Mod] The Orange dragon will spawn soon!
[21:43:12] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5348.method_27658(net.minecraft.class_5348$class_5246, net.minecraft.class_2583)" because "$$0" is null
	at net.minecraft.class_5223.method_27476(class_5223.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_5225.method_27488(class_5225.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_27525(class_327.java:314) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_55801(class_329.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55813(class_9080.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55812(class_9080.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55813(class_9080.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_9080.method_55809(class_9080.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:896) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.4.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) [JavaWrapper.jar:?]
[21:43:14] [Render thread/INFO]: Stopping worker threads
```

**Comment by AzureAaron** [comment]
Hi, I finally tracked the issue down and it has been fixed in the latest commit. Apologies for having taken a while to fix this, you can compile the mod yourself for now or wait until I release 1.5.0 Beta 2 later this week. :)
